### ISSUE TITLE
Убрать проверки flake8 и mypy для тестов

### ISSUE THREAD

**Issue by cofob** [fire-square/autodonate#78]

**Comment by PerchunPak** [comment]
Нет. Деббагинг чего угодно, даже тестов, становится в 1000 раз легче с минимальными объяснениями и типами.

**Comment by cofob** [comment]
> Нет. Деббагинг чего угодно, даже тестов, становится в 1000 раз легче с минимальными объяснениями и типами.

Зачем докстринги в тестах? Зачем проверки типов в тестах? Я понимаю для чего это делается в продакшен-коде, но в тесты то зачем тащить?

**Comment by PerchunPak** [comment]
Деббагинг и исправления становятся в 1000 раз легче. В любом случае не тяжело добавить и то, и другое.

**Comment by cofob** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Убрать проверки flake8 и mypy для тестов](https://trello.com/c/0fPFA3HM/9-%D1%83%D0%B1%D1%80%D0%B0%D1%82%D1%8C-%D0%BF%D1%80%D0%BE%D0%B2%D0%B5%D1%80%D0%BA%D0%B8-flake8-%D0%B8-mypy-%D0%B4%D0%BB%D1%8F-%D1%82%D0%B5%D1%81%D1%82%D0%BE%D0%B2)

**Comment by cofob** [comment]
> Деббагинг и исправления становятся в 1000 раз легче. В любом случае не тяжело добавить и то, и другое.

Добавь тесты в исключения

**Comment by PerchunPak** [comment]
> > Деббагинг и исправления становятся в 1000 раз легче. В любом случае не тяжело добавить и то, и другое.
> 
> Добавь тесты в исключения

Деббагинг и исправления становятся в 1000 раз легче. В любом случае не тяжело добавить и то, и другое.

**Comment by cofob** [comment]
> > > Деббагинг и исправления становятся в 1000 раз легче. В любом случае не тяжело добавить и то, и другое.
> > 
> > 
> > Добавь тесты в исключения
> 
> Деббагинг и исправления становятся в 1000 раз легче. В любом случае не тяжело добавить и то, и другое.

Докстринги в тестах не нужны, они только замедляют процесс создания тестов, как и mypy.

**Comment by PerchunPak** [comment]
> > > > Деббагинг и исправления становятся в 1000 раз легче. В любом случае не тяжело добавить и то, и другое.
> > > 
> > > 
> > > Добавь тесты в исключения
> > 
> > 
> > Деббагинг и исправления становятся в 1000 раз легче. В любом случае не тяжело добавить и то, и другое.
> 
> Докстринги в тестах не нужны, они только замедляют процесс создания тестов, как и mypy.

Чем же? Ты просто пишешь пару дополнительных слов. `Этот тест проверяет корректность какого-то метода.` Это все что нужно написать, тебе не нужно писать прям гайды как пользоваться.

А типы это вообще секунда дела, если IDE не подсказывает - `print(type(variable))`. Зато потом смотреть что сломалось будет в тысячу раз легче.

**Comment by cofob** [comment]
Тесты не ломаются. Ты только усложняешь их написание. В них не требуется какой либо безопасности и документации.

**Comment by PerchunPak** [comment]
Да. А потом понять почему этот тест сломался и как его починить будет намного сложнее без типов. Особенно если ты не можешь дебажить и/или не хочешь делать это через `Pdb`.

**Comment by cofob** [comment]
> намного

Это не так. Даже дебажить не нужно. Ты преувеличиваешь ситуацию.

**Comment by PerchunPak** [comment]
Я как человек который захотел законтрибьютить в проект с 500 тестами и сломав 5 не смогши понять что они делают заявляю что не преувеличиваю.

А если серьезно, я реально не понял почему оно сломалось и как починить. И моя ли вина в том что оно сломалось?

**Comment by cofob** [comment]
Доки - название теста. `test_some_thing_returns_true` - не описание?
`mypy` в тестах категорически не нужен.

**Comment by PerchunPak** [comment]
Договорились что оставляем.
