### ISSUE TITLE
Переделать автоматическую документацию

### ISSUE THREAD

**Issue by cofob** [fire-square/autodonate#85]
С ней возникает множество проблем, она малоинформативна и часто ломается. В любом случае придётся писать ручную документацию. 

Вот например как [это](https://readthedocs.org/projects/autodonate/builds/16738618/) чинить?

**Comment by PerchunPak** [comment]
Согласен, нужно переделать документацию на вручную написанную. Тем не менее `flake8` отключать я не собираюсь.

**Comment by cofob** [comment]
> Согласен, нужно переделать документацию на вручную написанную. Тем не менее `flake8` отключать я не собираюсь.

Я говорил тут про `flake8`?

**Comment by cofob** [comment]
Для флэйка можно сделать игнорирование пустых файлов, т.к. они могут быть просто структурными и там не будет нужна документация.

**Comment by PerchunPak** [comment]
Если ты про `__init__.py`, то там нужно хранить короткое описание для папки где этот файл находится. Вообще это можно назвать `package description`.

**Comment by cofob** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Переделать автоматическую документацию](https://trello.com/c/RVEcfgbr/10-%D0%BF%D0%B5%D1%80%D0%B5%D0%B4%D0%B5%D0%BB%D0%B0%D1%82%D1%8C-%D0%B0%D0%B2%D1%82%D0%BE%D0%BC%D0%B0%D1%82%D0%B8%D1%87%D0%B5%D1%81%D0%BA%D1%83%D1%8E-%D0%B4%D0%BE%D0%BA%D1%83%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%86%D0%B8%D1%8E)
